# Generated by Django 3.1.1 on 2022-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meet_infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_number', models.CharField(max_length=200)),
                ('meet_name', models.CharField(max_length=200)),
                ('meet_agenda1', models.TextField()),
                ('meet_agenda2', models.TextField()),
                ('meet_agenda3', models.TextField()),
                ('meet_agenda4', models.TextField()),
                ('meet_agenda5', models.TextField()),
                ('total_time', models.CharField(max_length=200)),
                ('next_time', models.CharField(max_length=200)),
                ('meet_record', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
