# Generated by Django 3.1.1 on 2022-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220117_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_id', models.CharField(max_length=200)),
                ('action_id', models.CharField(max_length=200)),
                ('item', models.TextField()),
                ('person', models.TextField()),
                ('dead_line', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_id', models.CharField(max_length=200)),
                ('agenda_id', models.CharField(max_length=200)),
                ('discussion', models.TextField()),
                ('decisions', models.TextField()),
                ('setting_time', models.DateField()),
                ('progress_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('meet_id', models.CharField(max_length=200)),
                ('meet_name', models.TextField()),
                ('meet_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('participants', models.TextField()),
                ('goal', models.TextField()),
                ('last_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='meet_infor',
        ),
    ]
