# Generated by Django 3.1.1 on 2022-01-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220123_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='dead_line',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='progress_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='setting_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meet',
            name='last_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_date',
            field=models.DateTimeField(),
        ),
    ]
