# Generated by Django 3.1.1 on 2022-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20220123_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='progress_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='setting_time',
            field=models.IntegerField(),
        ),
    ]
