# Generated by Django 3.1.1 on 2022-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20220123_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='dead_line',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='person',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='agenda_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='progress_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
