# Generated by Django 3.1.3 on 2022-01-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
