# Generated by Django 3.1.3 on 2022-02-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_id', models.CharField(max_length=200)),
                ('action_id', models.CharField(max_length=200)),
                ('action_title', models.TextField(null=True)),
                ('person', models.TextField(null=True)),
                ('dead_line', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_id', models.CharField(max_length=200)),
                ('agenda_id', models.CharField(max_length=200)),
                ('agenda_title', models.TextField(default='')),
                ('agenda_status', models.CharField(max_length=200)),
                ('discussion', models.TextField(null=True)),
                ('decisions', models.TextField(null=True)),
                ('setting_time', models.IntegerField()),
                ('progress_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('meet_id', models.CharField(max_length=200)),
                ('meet_title', models.TextField()),
                ('meet_date', models.DateTimeField()),
                ('meet_status', models.CharField(max_length=200)),
                ('rm_status', models.CharField(max_length=200)),
                ('participants', models.TextField()),
                ('goal', models.TextField()),
                ('last_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_id', models.CharField(max_length=200)),
                ('check_id', models.CharField(max_length=200)),
                ('ownership', models.CharField(max_length=200)),
                ('participation', models.CharField(max_length=200)),
                ('efficiency', models.CharField(max_length=200)),
                ('productivity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('nickname', models.CharField(max_length=200, null=True)),
                ('provider', models.CharField(max_length=200, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('img', models.CharField(max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
