# Generated by Django 3.1.3 on 2022-02-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('cause', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(null=True),
        ),
    ]
