# Generated by Django 3.1.3 on 2022-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20220225_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='goal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='participants',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='rm_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
