# Generated by Django 3.1.3 on 2022-02-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20220209_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
