# Generated by Django 3.1.3 on 2022-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20220221_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='secession',
            name='reg_date',
            field=models.DateTimeField(null=True),
        ),
    ]
