# Generated by Django 3.1.3 on 2022-02-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20220227_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='user_id',
        ),
    ]
