# Generated by Django 3.1.3 on 2022-02-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_action_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfcheck',
            name='user_id',
            field=models.ForeignKey(db_column='id', default=1, on_delete=django.db.models.deletion.CASCADE, to='pybo.user'),
            preserve_default=False,
        ),
    ]
