# Generated by Django 3.1.3 on 2022-02-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_selfcheck_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='selfcheck',
            name='user_id',
        ),
    ]
