# Generated by Django 3.1.3 on 2022-03-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20220227_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='decisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='discussion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
