# Generated by Django 3.1.3 on 2022-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20220301_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfcheck',
            name='efficiency',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selfcheck',
            name='ownership',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selfcheck',
            name='participation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selfcheck',
            name='productivity',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
