# Generated by Django 3.1.3 on 2022-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_auto_20220302_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secession',
            name='cause',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
