# Generated by Django 3.1.3 on 2022-03-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20220302_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agenda_status',
            field=models.CharField(default='Y', max_length=200),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='progress_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='setting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
