# Generated by Django 3.1.3 on 2022-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_auto_20220307_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='dead_line',
            field=models.DateTimeField(null=True),
        ),
    ]
