# Generated by Django 3.1.3 on 2022-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_auto_20220307_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='person',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
