# Generated by Django 3.1.3 on 2022-03-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_auto_20220307_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_time', models.IntegerField(blank=True, default='', null=True)),
                ('agenda_id', models.ForeignKey(db_column='agenda_id', on_delete=django.db.models.deletion.CASCADE, to='pybo.agenda')),
            ],
        ),
    ]
