# Generated by Django 3.1.3 on 2022-03-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0017_agenda_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfcheck',
            old_name='efficiency',
            new_name='check1',
        ),
        migrations.RenameField(
            model_name='selfcheck',
            old_name='ownership',
            new_name='check10',
        ),
        migrations.RenameField(
            model_name='selfcheck',
            old_name='participation',
            new_name='check2',
        ),
        migrations.RenameField(
            model_name='selfcheck',
            old_name='productivity',
            new_name='check3',
        ),
        migrations.AddField(
            model_name='selfcheck',
            name='check4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selfcheck',
            name='check5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selfcheck',
            name='check6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selfcheck',
            name='check7',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selfcheck',
            name='check8',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selfcheck',
            name='check9',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
