# Generated by Django 3.1.3 on 2022-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0018_auto_20220309_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agenda_status',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='decisions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='discussion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='order_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='progress_time',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='setting_time',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
