# Generated by Django 3.1.3 on 2022-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0019_auto_20220309_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='progress_time',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
