# Generated by Django 3.1.3 on 2022-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0020_auto_20220309_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='setting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda_progress',
            name='progress_time',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
